DROP TABLE IF EXISTS server_report;

CREATE TABLE server_report (
  id BIGINT NOT NULL AUTO_INCREMENT,
  download DOUBLE NOT NULL,
  upload DOUBLE NOT NULL,
  ping DOUBLE NOT NULL,
  recorded_at TIMESTAMP NOT NULL,
  PRIMARY KEY (id)
);