export const FETCH_RECORDS = "FETCH_RECORDS";
export const NEW_RECORD = "NEW_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";
export const FETCH_SERVER_REPORTS = "FETCH_SERVER_REPORTS";
export const DELETE_SERVER_REPORTS = "DELETE_SERVER_REPORTS";
